husband(mohammed, husband).
wife(blabla, none).
daughter(none, daughter).
sonsonson(none, none).
sonsondaughter(none, none).
son(ha, son).
sonson(none, none).
sondaughter(none, none).
father(none, none).
fatherfather(none, none).
fathermother(none, none).
mother(amina, mother).
mothermother(none, none).
realsister(realsis, realsister).
parentalsister(iexist, none).
realbrother(realbro, realbrother).
parentalbrother(none, none).
maternalsister(sis, maternalsister).
maternalbrother(hey1, none).
